services:
  facilities-api:
    build: .
    container_name: facilities-api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "on-failure"
    networks:
      - facilities-api

  db:
    image: postgis/postgis:13-3.1
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - facilities-api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - facilities-api
    networks:
      - facilities-api

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - facilities-api
      - frontend
    networks:
      - facilities-api
    
  
  redis:
    image: "redis:alpine"
    container_name: redis_container
    networks:
      - facilities-api

networks:
  facilities-api:
    driver: bridge

volumes:
  postgres_data: