# Generated by Django 4.2.13 on 2024-09-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drones',
            options={'verbose_name_plural': 'Drones'},
        ),
        migrations.AlterModelOptions(
            name='healthfacilities',
            options={'verbose_name_plural': 'Health Facilities'},
        ),
    ]
