# Generated by Django 4.2.13 on 2024-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_alter_drones_options_alter_healthfacilities_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drones',
            name='idle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drones',
            name='routes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
