# Generated by Django 4.2.13 on 2024-09-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0003_drones_idle_drones_routes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drones',
            old_name='idle',
            new_name='ocuppied',
        ),
    ]
