# Generated by Django 4.2.13 on 2024-09-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0004_rename_idle_drones_ocuppied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drones',
            old_name='routes',
            new_name='waypoints',
        ),
    ]
