# Generated by Django 4.2.13 on 2024-09-18 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0005_rename_routes_drones_waypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drones',
            name='id',
        ),
        migrations.AddField(
            model_name='drones',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
