# Generated by Django 4.2.13 on 2024-09-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0006_remove_drones_id_drones_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drones',
            old_name='ocuppied',
            new_name='occupied',
        ),
    ]
