# Generated by Django 4.2.13 on 2024-09-19 08:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0007_rename_ocuppied_drones_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drones',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='drones',
            name='current_charge',
        ),
        migrations.AddField(
            model_name='drones',
            name='departure',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='drones',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
