# Generated by Django 4.2.13 on 2024-10-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0009_alter_drones_departure_alter_drones_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='drones',
            name='waypoint_tracker',
            field=models.IntegerField(default=0),
        ),
    ]
