# Generated by Django 4.2.13 on 2024-10-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0010_drones_waypoint_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drones',
            old_name='waypoint_tracker',
            new_name='drone_tracker',
        ),
    ]
