# Generated by Django 4.2.13 on 2024-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0011_rename_waypoint_tracker_drones_drone_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='drone_tracker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
