# Generated by Django 4.2.13 on 2026-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0012_alter_drones_drone_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='name',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='drones',
            name='occupied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='drones',
            name='serial_no',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='amenity',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='healthcare',
            field=models.CharField(blank=True, db_index=True, max_length=167, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='drones',
            index=models.Index(fields=['occupied'], name='navigate_dr_occupie_98b86e_idx'),
        ),
        migrations.AddIndex(
            model_name='drones',
            index=models.Index(fields=['name'], name='navigate_dr_name_0ce2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacilities',
            index=models.Index(fields=['name'], name='navigate_he_name_c0c458_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacilities',
            index=models.Index(fields=['healthcare'], name='navigate_he_healthc_0f6ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='healthfacilities',
            index=models.Index(fields=['amenity'], name='navigate_he_amenity_96c7cd_idx'),
        ),
    ]
